apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxi-booking
  namespace: taxi
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  taxi-booking
  template:
    metadata:
      labels:
        app:  taxi-booking
    spec:
      imagePullSecrets:
      - name: jfrog-cred
      containers:
      - name:  taxi-booking
        image: trialqrbazk.jfrog.io/taxiapp001-docker-local/taxiapp:1.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
