apiVersion: v1
kind: Secret
metadata:
  name: jfrog-cred
  namespace: taxi
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ0cmlhbHFyYmF6ay5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiTWpFemFqRmhNRFV3TkVCeVlXZG9kV2x1YzNSbFkyZ3VZMjl0T2tSdlkydGxja0F4TWpNPSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
